export {default as BrowseProducts} from './browseProducts'
export {default as SingleProduct} from './singleProduct'
export {default as Login } from './login'
export {default as Navigation } from './navigation'
export {default as Profile } from './profile'
export { Footer } from './footer'
export { About } from './about'